### ISSUE TITLE
Origin of source?

### ISSUE THREAD

**Issue by barrystyle** [slax0r/gszminer#1]
This is a blatant rip of https://github.com/dmaxl/cgminer. 

All you've done is change the name and remove scrypt parameter.
You havent even spent the 5 minutes to fix the hashrate reporting bug.
Get this shit off github.

**Comment by slax0r** [comment]
Perhaps you should take 5 minutes to actually review the source.  cgminer doesn't even support Scrypt or the Gridseed or Zeus  miners.  Also if you had taken the time to check the source, you'd notice that there isnt a hashrate reporting bug in gszminer, because it isnt based on cgminer.

Your FUD is not welcome here.

**Comment by barrystyle** [comment]
CGMiner 4.3.5 with Scrypt and support for Gridseed and Zeus ASICs (https://github.com/dmaxl/cgminer)

![gsz__](https://cloud.githubusercontent.com/assets/14147070/13198506/30576540-d845-11e5-8c47-c0c0c715d8ad.png)
![cg___](https://cloud.githubusercontent.com/assets/14147070/13198507/3059d5c8-d845-11e5-8a30-02dc0a147523.png)

Dunno boss; look identical to me. Your transparency is unbelievable.

**Comment by slax0r** [comment]
Dunno boss, looks just like sgminer and to a large part bfgminer too me, the primary foundations of gszminer by the way.  Are you posting your asinine comments to them as well?

If you really must know the origins, gszminer is a compilation of bits and peices from the ancient cgminer that you show above, some excellent improvements from sgminer and a smattering of bfgminer.  So if you are only focused on the UI then you definitely have no idea how ignorant you sound.  Take a stroll through the code, see what fixes have been made and what else is different. 

This is an open source project, anyone is welcome to contribute fixes and improvements at anytime or fork it off and completely do their own thing.  I did my own thing because I needed it do a certain specialized thing and put it here on Github to help the coin mining community.

Do you contribute anything to any such projects here other than your ignorance?

It is criticism like yours that keep people like myself, lukejr and ckolivas from doing more.

Since you don't seem to really be paying attention to the grander scheme, check out bfgminer and the newer versions of cgminer.  I am an active contributor on both.

I suggest if you have a better idea, perhaps you should post your own project. I suspect that if you do, you probably wont do it from scratch.
